  // ============================================
  // 応用情報技術者試験 - テクノロジ系
  // ============================================
  {
    category_id: CATEGORY_IDS.ap_technology,
    question_text: 'システム開発におけるアジャイル開発手法の特徴として、最も適切なものはどれか。',
    choice_a: '詳細な設計書を作成してから実装を開始する',
    choice_b: '短いイテレーションで継続的に機能を追加・改善する',
    choice_c: 'すべての要件を最初に確定してから開発を開始する',
    choice_d: '開発完了後に一括でテストを実施する',
    correct_answer: 'B' as const,
    explanation: 'アジャイル開発は、短いイテレーション（スプリント）で継続的に機能を追加・改善し、顧客との協調を重視する開発手法です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_technology,
    question_text: 'マイクロサービスアーキテクチャの利点として、最も適切なものはどれか。',
    choice_a: '単一の大きなアプリケーションとして管理が容易',
    choice_b: '各サービスを独立して開発・デプロイできる',
    choice_c: 'すべてのサービスが同じ技術スタックを使用する必要がある',
    choice_d: 'サービス間の通信が不要',
    correct_answer: 'B' as const,
    explanation: 'マイクロサービスアーキテクチャでは、各サービスが独立して開発・デプロイ・スケールできるため、チームの独立性と開発速度の向上が期待できます。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_technology,
    question_text: 'DevOpsの実践において、CI/CDパイプラインの主な目的はどれか。',
    choice_a: '開発と運用の組織を分離する',
    choice_b: 'コードの品質を下げて開発速度を上げる',
    choice_c: '自動化により、コードの統合・テスト・デプロイを迅速かつ確実に実行する',
    choice_d: '手動でのデプロイプロセスを維持する',
    correct_answer: 'C' as const,
    explanation: 'CI/CDパイプラインは、継続的インテグレーション（CI）と継続的デプロイ（CD）を自動化し、コードの統合・テスト・デプロイを迅速かつ確実に実行するための仕組みです。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_technology,
    question_text: 'コンテナオーケストレーションツールであるKubernetesの主な機能として、適切でないものはどれか。',
    choice_a: 'コンテナの自動スケーリング',
    choice_b: 'コンテナの自動復旧',
    choice_c: 'コンテナ間のネットワーク管理',
    choice_d: 'コンテナの手動起動のみ',
    correct_answer: 'D' as const,
    explanation: 'Kubernetesは、コンテナの自動スケーリング、自動復旧、ネットワーク管理、ロードバランシングなど、コンテナの運用を自動化する機能を提供します。手動起動のみというのは誤りです。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_technology,
    question_text: 'RESTful APIの設計原則として、適切でないものはどれか。',
    choice_a: 'ステートレスな通信',
    choice_b: '統一されたインターフェース',
    choice_c: 'リソース指向の設計',
    choice_d: 'サーバー側でセッション状態を保持する',
    correct_answer: 'D' as const,
    explanation: 'RESTful APIはステートレスな通信を原則としており、サーバー側でセッション状態を保持しません。各リクエストは独立して処理されます。',
    difficulty: 3,
  },
  // ============================================
  // 応用情報技術者試験 - マネジメント系
  // ============================================
  {
    category_id: CATEGORY_IDS.ap_management,
    question_text: 'ITILにおける「インシデント管理」の主な目的はどれか。',
    choice_a: 'サービスの可用性を向上させる',
    choice_b: '問題の根本原因を特定する',
    choice_c: 'サービス中断を迅速に復旧し、通常のサービス運用を可能な限り早く再開する',
    choice_d: '変更を管理する',
    correct_answer: 'C' as const,
    explanation: 'インシデント管理は、サービス中断や品質低下を迅速に復旧し、通常のサービス運用を可能な限り早く再開することを目的とします。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_management,
    question_text: 'プロジェクトマネジメントにおける「リスク管理」のプロセスとして、正しい順序はどれか。',
    choice_a: 'リスク識別 → リスク分析 → リスク対応計画 → リスク監視',
    choice_b: 'リスク対応計画 → リスク識別 → リスク分析 → リスク監視',
    choice_c: 'リスク監視 → リスク識別 → リスク分析 → リスク対応計画',
    choice_d: 'リスク分析 → リスク識別 → リスク監視 → リスク対応計画',
    correct_answer: 'A' as const,
    explanation: 'リスク管理は、まずリスクを識別し、次に分析して影響度と発生確率を評価し、対応計画を立て、最後に監視・制御する流れで実施します。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_management,
    question_text: 'サービスマネジメントにおける「SLA（Service Level Agreement）」の説明として、最も適切なものはどれか。',
    choice_a: 'サービス提供者と顧客の間で合意されたサービスの品質レベル',
    choice_b: 'システムの技術仕様を定義した文書',
    choice_c: 'プロジェクトのスケジュールを定義した文書',
    choice_d: 'セキュリティポリシーを定義した文書',
    correct_answer: 'A' as const,
    explanation: 'SLAは、サービス提供者と顧客の間で合意された、サービスの品質レベル（可用性、応答時間、解決時間など）を定義した合意書です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_management,
    question_text: 'アジャイルプロジェクトマネジメントにおける「スプリント」の説明として、最も適切なものはどれか。',
    choice_a: 'プロジェクト全体の期間',
    choice_b: '短い時間枠（通常1〜4週間）で、特定の機能を完成させる反復的な開発サイクル',
    choice_c: 'バグ修正のみを行う期間',
    choice_d: '計画のみを行う期間',
    correct_answer: 'B' as const,
    explanation: 'スプリントは、アジャイル開発における短い時間枠（通常1〜4週間）で、特定の機能を計画・開発・テスト・レビューする反復的な開発サイクルです。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_management,
    question_text: '変更管理プロセスにおいて、「緊急変更」の特徴として、最も適切なものはどれか。',
    choice_a: '通常の変更管理プロセスを完全にスキップする',
    choice_b: '通常の変更管理プロセスを簡略化して迅速に承認・実施する',
    choice_c: '変更を実施しない',
    choice_d: '変更管理プロセスを通常通り実施する',
    correct_answer: 'B' as const,
    explanation: '緊急変更は、重大なインシデントの解決など、緊急を要する場合に、通常の変更管理プロセスを簡略化して迅速に承認・実施する変更です。',
    difficulty: 3,
  },
  // ============================================
  // 応用情報技術者試験 - ストラテジ系
  // ============================================
  {
    category_id: CATEGORY_IDS.ap_strategy,
    question_text: 'デジタルトランスフォーメーション（DX）の推進において、最も重要な要素はどれか。',
    choice_a: '最新の技術を導入すること',
    choice_b: '組織文化の変革とビジネスモデルの再構築',
    choice_c: 'IT部門のみで推進すること',
    choice_d: '既存システムをそのまま維持すること',
    correct_answer: 'B' as const,
    explanation: 'DXは単なる技術導入ではなく、組織文化の変革とビジネスモデルの再構築を通じて、デジタル技術を活用して価値を創出することが重要です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_strategy,
    question_text: 'ビジネスアーキテクチャの設計において、「ビジネスプロセス」の定義として、最も適切なものはどれか。',
    choice_a: 'ハードウェアの構成',
    choice_b: 'ビジネス目標を達成するための一連の関連する活動やタスク',
    choice_c: 'ソフトウェアのコード',
    choice_d: 'ネットワークの設定',
    correct_answer: 'B' as const,
    explanation: 'ビジネスプロセスは、ビジネス目標を達成するための一連の関連する活動やタスクの集合体です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_strategy,
    question_text: 'ITガバナンスの目的として、最も適切なものはどれか。',
    choice_a: 'IT部門の独立性を高める',
    choice_b: 'IT投資の価値を最大化し、リスクを適切に管理する',
    choice_c: 'IT部門の予算を削減する',
    choice_d: 'IT部門の人員を削減する',
    correct_answer: 'B' as const,
    explanation: 'ITガバナンスは、IT投資の価値を最大化し、リスクを適切に管理し、組織の戦略目標との整合性を確保するための仕組みです。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_strategy,
    question_text: 'データドリブン経営において、重要な要素として、適切でないものはどれか。',
    choice_a: 'データの収集と分析',
    choice_b: 'データに基づいた意思決定',
    choice_c: 'データの品質管理',
    choice_d: 'データを無視した直感的な意思決定',
    correct_answer: 'D' as const,
    explanation: 'データドリブン経営は、データの収集・分析・品質管理を行い、データに基づいた意思決定を行う経営手法です。直感的な意思決定は適切ではありません。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.ap_strategy,
    question_text: 'エンタープライズアーキテクチャ（EA）の4つのアーキテクチャ領域として、正しい組み合わせはどれか。',
    choice_a: 'ビジネス、データ、アプリケーション、テクノロジ',
    choice_b: 'ハードウェア、ソフトウェア、ネットワーク、データベース',
    choice_c: '開発、運用、保守、管理',
    choice_d: '計画、設計、実装、テスト',
    correct_answer: 'A' as const,
    explanation: 'EAの4つのアーキテクチャ領域は、ビジネスアーキテクチャ、データアーキテクチャ、アプリケーションアーキテクチャ、テクノロジアーキテクチャです。',
    difficulty: 3,
  },
];
