// 応用情報技術者試験の問題データ

// カテゴリID
export const CATEGORY_IDS = {
  technology: '00000000-0000-0000-0000-000000000021',
  management: '00000000-0000-0000-0000-000000000022',
  strategy: '00000000-0000-0000-0000-000000000023',
};

// 問題データ型
export type Question = {
  category_id: string;
  question_text: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_answer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: number;
};

// 応用情報技術者試験の問題データ
export const questions: Question[] = [
  // テクノロジ系（10問）
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'システム開発におけるアジャイル開発手法の特徴として、最も適切なものはどれか。',
    choice_a: '詳細な仕様書を作成してから開発を開始する',
    choice_b: '短いイテレーションで開発を繰り返し、継続的に改善する',
    choice_c: '開発工程を順次実行するウォーターフォール型の開発',
    choice_d: 'すべての機能を一度にリリースする',
    correct_answer: 'B' as const,
    explanation: 'アジャイル開発は、短いスプリント（イテレーション）で開発を繰り返し、顧客フィードバックを取り入れながら継続的に改善していく開発手法です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'マイクロサービスアーキテクチャの利点として、最も適切なものはどれか。',
    choice_a: 'すべてのサービスを1つのプロセスで実行できる',
    choice_b: 'サービス間の独立性が高く、個別にスケールやデプロイが可能',
    choice_c: 'サービス間の通信が不要になる',
    choice_d: 'データベースを1つに統一できる',
    correct_answer: 'B' as const,
    explanation: 'マイクロサービスアーキテクチャでは、各サービスが独立して開発・デプロイ・スケールできるため、柔軟性と拡張性が向上します。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'DevOpsの実践において、CI/CDパイプラインの主な目的はどれか。',
    choice_a: '開発環境と本番環境を分離すること',
    choice_b: 'コードの品質を自動的にテストし、自動的にデプロイすること',
    choice_c: '開発チームと運用チームを分離すること',
    choice_d: 'すべてのコードを手動でテストすること',
    correct_answer: 'B' as const,
    explanation: 'CI/CD（Continuous Integration/Continuous Deployment）は、コードの自動ビルド・テスト・デプロイを実現し、開発から本番までのプロセスを自動化します。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'コンテナオーケストレーションツールであるKubernetesの主な機能として、最も適切なものはどれか。',
    choice_a: 'コンテナイメージの作成',
    choice_b: 'コンテナの自動スケーリング、ロードバランシング、自己修復',
    choice_c: 'コンテナのビルドとテスト',
    choice_d: 'コンテナのコード編集',
    correct_answer: 'B' as const,
    explanation: 'Kubernetesは、コンテナの自動スケーリング、ロードバランシング、障害時の自動復旧、サービスディスカバリなどの機能を提供するオーケストレーションツールです。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'RESTful APIの設計原則として、最も適切なものはどれか。',
    choice_a: 'すべての操作をPOSTメソッドで実装する',
    choice_b: 'ステートレスな通信、リソース指向の設計、適切なHTTPメソッドの使用',
    choice_c: 'すべてのデータを1つのエンドポイントで取得する',
    choice_d: 'クライアント側でセッション管理を行う',
    correct_answer: 'B' as const,
    explanation: 'RESTful APIは、ステートレスな通信、リソース指向の設計、適切なHTTPメソッド（GET、POST、PUT、DELETE）の使用を原則とします。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'データベースの正規化において、第3正規形（3NF）の条件として、最も適切なものはどれか。',
    choice_a: 'すべての属性が主キーに完全関数従属している',
    choice_b: '第2正規形であり、かつ非キー属性が主キーに推移的関数従属していない',
    choice_c: 'すべての属性が1つのテーブルに格納されている',
    choice_d: '外部キー制約が設定されている',
    correct_answer: 'B' as const,
    explanation: '第3正規形は、第2正規形を満たし、かつ非キー属性が主キーに対して推移的関数従属していない状態です。これにより、データの冗長性をさらに削減できます。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'クラウドコンピューティングのサービスモデルであるIaaS、PaaS、SaaSの違いとして、最も適切なものはどれか。',
    choice_a: 'IaaSはアプリケーションのみ、PaaSはプラットフォームのみ、SaaSはインフラのみを提供する',
    choice_b: 'IaaSはインフラ、PaaSはプラットフォーム、SaaSはアプリケーションを提供する',
    choice_c: 'すべて同じサービスを提供する',
    choice_d: 'IaaSは最も高価で、SaaSは最も安価である',
    correct_answer: 'B' as const,
    explanation: 'IaaS（Infrastructure as a Service）は仮想マシンやストレージなどのインフラ、PaaS（Platform as a Service）は開発・実行環境、SaaS（Software as a Service）はアプリケーションを提供します。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'セキュリティにおけるゼロトラストアーキテクチャの考え方として、最も適切なものはどれか。',
    choice_a: '内部ネットワークは常に信頼できると仮定する',
    choice_b: 'すべてのトラフィックを信頼せず、常に検証と認証を行う',
    choice_c: '外部ネットワークのみを監視する',
    choice_d: 'パスワードのみで認証を行う',
    correct_answer: 'B' as const,
    explanation: 'ゼロトラストは「何も信頼しない」という考え方で、内部・外部を問わずすべてのトラフィックとアクセスを検証・認証・監視するセキュリティモデルです。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: '分散システムにおけるCAP定理の説明として、最も適切なものはどれか。',
    choice_a: 'Consistency、Availability、Partition toleranceの3つを同時に満たすことはできない',
    choice_b: 'すべての分散システムは3つの特性を同時に満たせる',
    choice_c: 'Consistencyのみが重要である',
    choice_d: 'Partition toleranceは不要である',
    correct_answer: 'A' as const,
    explanation: 'CAP定理は、分散システムにおいてConsistency（一貫性）、Availability（可用性）、Partition tolerance（分断耐性）の3つを同時に満たすことはできないという定理です。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.technology,
    question_text: 'API Gatewayパターンの主な役割として、最も適切なものはどれか。',
    choice_a: 'すべてのAPIリクエストを1つのサービスに転送する',
    choice_b: '認証・認可、レート制限、ルーティング、モニタリングなどの横断的関心事を一元管理',
    choice_c: 'データベースへの直接アクセスを提供する',
    choice_d: 'フロントエンドのコードを生成する',
    correct_answer: 'B' as const,
    explanation: 'API Gatewayは、複数のマイクロサービスへのエントリーポイントとして、認証・認可、レート制限、ロードバランシング、モニタリングなどの共通機能を一元管理します。',
    difficulty: 3,
  },

  // マネジメント系（5問）
  {
    category_id: CATEGORY_IDS.management,
    question_text: 'プロジェクトマネジメントにおけるスコープクリープの説明として、最も適切なものはどれか。',
    choice_a: 'プロジェクトのスコープが段階的に拡大していく現象',
    choice_b: 'プロジェクトの予算が削減されること',
    choice_c: 'プロジェクトのスケジュールが短縮されること',
    choice_d: 'プロジェクトチームの人数が減ること',
    correct_answer: 'A' as const,
    explanation: 'スコープクリープは、プロジェクトの要件や成果物が正式な変更管理プロセスを経ずに段階的に拡大していく現象で、プロジェクトの失敗要因となります。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.management,
    question_text: 'ITILにおける「変更管理（Change Management）」の主な目的として、最も適切なものはどれか。',
    choice_a: 'すべての変更を即座に実施する',
    choice_b: '変更によるリスクを最小化し、ビジネス価値を最大化する',
    choice_c: '変更を一切許可しない',
    choice_d: '変更の記録を残さない',
    correct_answer: 'B' as const,
    explanation: '変更管理は、ITサービスの変更を統制された方法で実施し、リスクを最小化しながらビジネス価値を最大化することを目的とします。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.management,
    question_text: 'アジャイル開発におけるスクラムの「スプリント」の説明として、最も適切なものはどれか。',
    choice_a: 'プロジェクト全体の期間',
    choice_b: '1〜4週間の固定期間で、完成可能な機能を開発する時間ボックス',
    choice_c: 'バグ修正のみを行う期間',
    choice_d: '計画のみを行う期間',
    correct_answer: 'B' as const,
    explanation: 'スプリントは、1〜4週間の固定期間で、完成可能な機能（インクリメント）を開発する時間ボックスです。各スプリントの終わりに完成した機能をリリースします。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.management,
    question_text: 'プロジェクトのリスクマネジメントにおいて、「リスク回避」の説明として、最も適切なものはどれか。',
    choice_a: 'リスクが発生した場合の影響を最小限に抑える',
    choice_b: 'リスクの原因となる活動を中止または変更する',
    choice_c: 'リスクを外部に移転する',
    choice_d: 'リスクを受け入れる',
    correct_answer: 'B' as const,
    explanation: 'リスク回避は、リスクの原因となる活動を中止または変更することで、リスクそのものを排除する戦略です。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.management,
    question_text: 'サービスマネジメントにおけるSLA（Service Level Agreement）の説明として、最も適切なものはどれか。',
    choice_a: 'サービス提供者と利用者間のサービス品質に関する合意',
    choice_b: 'サービスの価格に関する合意',
    choice_c: 'サービスの提供期間に関する合意',
    choice_d: 'サービスの提供場所に関する合意',
    correct_answer: 'A' as const,
    explanation: 'SLAは、サービス提供者と利用者間で、サービスの可用性、パフォーマンス、応答時間などの品質指標について合意した文書です。',
    difficulty: 2,
  },

  // ストラテジ系（5問）
  {
    category_id: CATEGORY_IDS.strategy,
    question_text: 'デジタルトランスフォーメーション（DX）の推進において、最も重要な要素はどれか。',
    choice_a: '最新の技術を導入すること',
    choice_b: 'ビジネスモデルや組織文化の変革を含む、経営戦略としての取り組み',
    choice_c: 'IT部門のみで推進すること',
    choice_d: '既存システムをそのまま維持すること',
    correct_answer: 'B' as const,
    explanation: 'DXは単なる技術導入ではなく、デジタル技術を活用してビジネスモデルや組織文化を変革し、競争優位性を獲得する経営戦略です。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.strategy,
    question_text: 'ビジネスアーキテクチャとITアーキテクチャの整合性を確保するためのアプローチとして、最も適切なものはどれか。',
    choice_a: 'ITアーキテクチャのみを重視する',
    choice_b: 'ビジネス戦略とIT戦略を連携させ、エンタープライズアーキテクチャ（EA）を構築する',
    choice_c: 'ビジネスアーキテクチャのみを重視する',
    choice_d: '両者を独立して設計する',
    correct_answer: 'B' as const,
    explanation: 'エンタープライズアーキテクチャ（EA）は、ビジネスアーキテクチャ、データアーキテクチャ、アプリケーションアーキテクチャ、テクノロジーアーキテクチャを統合的に設計し、ビジネスとITの整合性を確保します。',
    difficulty: 4,
  },
  {
    category_id: CATEGORY_IDS.strategy,
    question_text: 'データドリブン経営において、最も重要な要素はどれか。',
    choice_a: '大量のデータを収集すること',
    choice_b: 'データを分析し、意思決定に活用すること',
    choice_c: 'データを保存すること',
    choice_d: 'データを削除すること',
    correct_answer: 'B' as const,
    explanation: 'データドリブン経営は、データを収集・分析し、その結果を意思決定に活用することで、経験や勘に頼らない科学的な経営を実現します。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.strategy,
    question_text: 'ITガバナンスの目的として、最も適切なものはどれか。',
    choice_a: 'IT部門の独立性を確保する',
    choice_b: 'IT投資の価値を最大化し、リスクを管理する',
    choice_c: 'IT部門の予算を削減する',
    choice_d: 'IT部門の人員を削減する',
    correct_answer: 'B' as const,
    explanation: 'ITガバナンスは、IT投資の価値を最大化し、リスクを適切に管理するための組織的な仕組みです。経営層とIT部門の意思決定プロセスを整備します。',
    difficulty: 3,
  },
  {
    category_id: CATEGORY_IDS.strategy,
    question_text: 'ビジネス継続計画（BCP）において、RTO（Recovery Time Objective）の説明として、最も適切なものはどれか。',
    choice_a: 'データの損失を許容できる最大時間',
    choice_b: 'システムやサービスを復旧するまでの目標時間',
    choice_c: 'システムのダウンタイムの合計時間',
    choice_d: 'バックアップの保存期間',
    correct_answer: 'B' as const,
    explanation: 'RTO（Recovery Time Objective）は、災害や障害発生後、システムやサービスを復旧するまでの目標時間です。ビジネスへの影響を最小限に抑えるために設定されます。',
    difficulty: 3,
  },
];
