name: OTA Update (Production)

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'components/**'
      - 'constants/**'
      - 'hooks/**'
      - 'lib/**'
      - 'types/**'
      - 'assets/**'
      - 'package.json'

jobs:
  ota_update_default:
    type: update
    params:
      branch: production
      platform: ios
      message: "OTA: ${{ github.event.head_commit.message }}"

  ota_update_ipass:
    type: update
    environment:
      APP_VARIANT: ipass
    params:
      branch: production-ipass
      platform: ios
      message: "OTA: ${{ github.event.head_commit.message }}"
